# Generated by Django 5.1.4 on 2024-12-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('key_features', models.TextField()),
                ('technology_stack', models.TextField()),
                ('my_role', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('code_link', models.URLField(blank=True, null=True)),
                ('live', models.URLField(blank=True, null=True)),
                ('challenges_and_learning', models.TextField()),
            ],
        ),
    ]
