# Generated by Django 5.1.4 on 2024-12-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnail/'),
        ),
    ]
